commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,10 +42,10 @@ jobs:
 
       - name: Execute tests via PHPUnit
         id: tests
-        run: php artisan test --filter Integration || echo "::set-output name=failed::true"
+        run: php artisan test --filter Integration || echo "FAILED=true" >> $GITHUB_ENV
 
       - name: Revert Commit if Tests Fail
-        if: steps.tests.outputs.failed == 'true'
+        if: ${{ env.FAILED == 'true' }}
         run: |
           git config user.name 'GitHub Actions'
           git config user.email 'actions@github.com'
