fresh dev branch + tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,6 +41,7 @@ jobs:
 
       - name: Execute tests via PHPUnit
         run: php artisan test --filter Integration
+        continue-on-error: false
 
       - name: Check test status
         run: |
@@ -48,6 +49,13 @@ jobs:
               echo "Tests passed. Proceeding with merge..."
             else
               echo "Tests failed. Preventing merge."
-              # Ваш код для предотвращения слияния, например, можно использовать GitHub API для добавления комментария или установки статуса.
-              exit 1
+                PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
+            API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments"
+            COMMENT="Tests failed. Merging is not allowed until tests pass."
+            TOKEN=${{ secrets.GITHUB_TOKEN }}
+            curl -X POST -d "{\"body\": \"$COMMENT\"}" -H "Authorization: token $TOKEN" -H "Content-Type: application/json" $API_URL
+            # Установка статуса "failure" для GitHub Actions
+            gh status create "Tests failed" -c "$GITHUB_SHA" -d "Tests failed" -s failure
+            exit 1
+
             fi
